services:
  # Frontend service to serve static files (HTML, CSS, JS)
  - type: web
    name: neet-jee-book-store-frontend
    env: static
    buildCommand: echo "No build step needed"
    publishDirectory: ./frontend
    envVars:
      - key: CASHFREE_APP_ID
        value: 605266b66d4c81295df88e013e662506  # Set Cashfree App ID
      - key: CASHFREE_SECRET_KEY
        value: cfsk_ma_prod_3d5c1e52a60832d47f1eb1af9045d1c2_4b948447  # Set Cashfree Secret Key
    plan: starter

  # Backend service to run the Node.js server
  - type: web
    name: neet-jee-book-store-backend
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: CASHFREE_APP_ID
        value: 605266b66d4c81295df88e013e662506  # Set Cashfree App ID
      - key: CASHFREE_SECRET_KEY
        value: cfsk_ma_prod_3d5c1e52a60832d47f1eb1af9045d1c2_4b948447  # Set Cashfree Secret Key
    plan: starter
